#Tabuada melhor
n = float(input('Digite um número para ver sua tabuada: '))
print('A tabuada de {} é: '.format(n))
print('{} x 1 = {:.2f}'.format(n, (n * 1)))
print('{} x 2 = {:.2f}'.format(n, (n * 2)))
print('{} x 3 = {:.2f}'.format(n, (n * 3)))
print('{} x 4 = {:.2f}'.format(n, (n * 4)))
print('{} x 5 = {:.2f}'.format(n, (n * 5)))
print('{} x 6 = {:.2f}'.format(n, (n * 6)))
print('{} x 7 = {:.2f}'.format(n, (n * 7)))
print('{} x 8 = {:.2f}'.format(n, (n * 8)))
print('{} x 9 = {:.2f}'.format(n, (n * 9)))
print('{} x 10 = {:.2f}'.format(n, (n * 10)))