dia=input('Que dia você nasceu?')
mês=input('Que mês você nasceu?')
ano=input('Que ano você nasceu?')
print('Você nasceu no dia', dia, 'do mês de', mês, 'do ano de', ano)
print('Você possui', int(2022)-int(ano), 'de idade')